### ISSUE TITLE
Box and Stripbox KeyError on two categories

### ISSUE THREAD

**Issue by lschaus0804** [justinbois/iqplot#8] opened 2020-11-24 02:18 UTC
`strip = iqplot.stripbox(
        data = df,
        q = "Yield",
        cats = ['Buffer', 'Solvent'],
)
`

Gives a key error on whatever the second category is. On their own the categories plot just fine.
The code works for strip plots but not for box or stripbox plots.
The dataframe used is composed of three columns "Solvent", "Buffer" and "Yield".
The column "Solvent" contains two categories and the column "Buffer" contains four categories for a total of 32 entries.

**Comment by justinbois** [comment] 2021-01-05 19:15
@lschaus0804 , can you please provide a minimal example for this?

I tried to reproduce it, but this works for me:

```python
import numpy as np
import pandas as pd

import iqplot

import bokeh.io

data = {
    "Yield": np.random.normal(10, 1, size=500),
    "Solvent": ["water"] * 200 + ["alcohol"] * 300,
    "Buffer": list(np.random.choice(["1 nM", "1 µM", "1 mM", "10 mM"], size=500)),
}

df = pd.DataFrame(data)

p = iqplot.stripbox(
    data=df,
    q='Yield',
    cats=['Buffer', 'Solvent'],
)

bokeh.io.show(p)
```

**Comment by lschaus0804** [comment] 2021-01-11 04:42
@justinbois Sure! Replicating the same data frame that I have with synthetic data I can reproduce it:

```python
data = {
    "Yield": np.random.normal(10, 1, size=32),
    "Solvent": ["EtOAc"] * 16 + ["THF"] * 16,
    "Buffer": (["M9"] * 4 + ["KPi"] * 4 + ["HEPES"] * 4 + ["Tris"] * 4)*2,    
}

df = pd.DataFrame(data)

p = iqplot.stripbox(
    data=df,
    q='Yield',
    cats=['Buffer', 'Solvent'],
)

bokeh.io.show(p)
```

So I figured out that it does not like the structure of my data, since this works:

```python
data = {
    "Yield": np.random.normal(10, 1, size=32),
    "Buffer": (["M9"] * 8 + ["KPi"] * 8 + ["HEPES"] * 8 + ["Tris"] * 8), 
    "Solvent": ["EtOAc"] * 16 + ["THF"] * 16,
   
}

df = pd.DataFrame(data)

p = iqplot.stripbox(
    data=df,
    q='Yield',
    cats=['Buffer', 'Solvent'],
)

bokeh.io.show(p)
```

Unfortunately, I cannot structure the data that way. I tried to shuffle the entries too, but it does not work with the original data frame:

```python
data = {
    "Yield": np.random.normal(10, 1, size=32),
    "Buffer": (["M9"] * 4 + ["KPi"] * 4 + ["HEPES"] * 4 + ["Tris"] * 4)*2, 
    "Solvent": ["EtOAc"] * 16 + ["THF"] * 16,
   
}

df = pd.DataFrame(data)
df = df.sample(frac = 1).reset_index(drop = True)

p = iqplot.stripbox(
    data=df,
    q='Yield',
    cats=['Buffer', 'Solvent'],
)

bokeh.io.show(p)
```

**Comment by justinbois** [comment] 2021-01-11 19:51
This is fixed. Will be included in next release.

Note that the `min_data` kwarg for both `iqplot.box()` and `iqplot.stripbox()` only allow boxes to be drawn if the number of data points is equal to or exceeds `min_data` for a given category. In there are fewer than `min_data` data points, the data are plotted as a strip plot.

**Closed as completed by justinbois** 2021-01-11 19:51 UTC
Labels: bug
